### PR TITLE
Brazilian Portuguese translation

### PR DESCRIPTION
**Pull request by rodzadra**

### CODE REVIEW

**Comment by nadar** [comment]
hi @rodzadra Thank you for the PR. This is a ready only repository which is getting push by https://github.com/luyadev/luya. Please make us a pull request from this repository, the kickstart is located here:

https://github.com/luyadev/luya/tree/master/envs/kickstarter

**Comment by rodzadra** [comment]
Hi @nadar.

Done. :)

**Comment by nadar** [comment]
Perfect, so you could commit those changes directly into your `rodzadra:brazilian-translations` branch in order to show them up in the https://github.com/luyadev/luya/pull/1236 PR.

**Comment by rodzadra** [comment]
@nadar it's done.

**Comment by nadar** [comment]
But the kickstarter translations are not listed here: https://github.com/luyadev/luya/pull/1236/files

**Pull request closed without merging**
