### PR TITLE
Consider using asset-packagist instead of fxp

### PR DESCRIPTION
**Pull request by samdark**
Installing fxp composer plugin globally complicates installation with another step. Also it's slow compared to https://asset-packagist.org.

I am not sure if config part is done properly (that's how it's done in Yii 2).

### CODE REVIEW

**Comment by nadar** [comment]
Looks good to me. The only downside of this change is that every project needs to maintain those two repeating alias entries, but it might worth it.

**Comment by samdark** [comment]
They are in the template so it should not take much effort to read and never change these :)

**Review by nadar — CHANGES_REQUESTED** [review]
Sure i total agree on this. It's more like "you have 50 projects with the same value in the config, but you know it could be somewhere in the `core` class defined for all of them".

Would you please add a changelog entry? So i will merge afterwards. Thank you very much @samdark!

**Comment by samdark** [comment]
Done. It should be tested though before merging.

**Review by nadar — APPROVED** [review]

**Comment by nadar** [comment]
Thanks @samdark

**Pull request merged**
