### PR TITLE
Create index.php

### PR DESCRIPTION
**Pull request by ScottHuangZL**
Help to redirect to public_html folder if user browser the root folder.
See .htaccess at root folder too.

### CODE REVIEW

**Comment by nadar** [comment]
Hi @ScottHuangZL Thank you very taking time thinking about solutions which could make luya better. I assume this is something very custom for your use case, because people should **always** map the virtual host to the public_html folder and never expose the root folder to the webserver.

**Comment by nadar** [comment]
Same as for: https://github.com/luyadev/luya-kickstarter/pull/33/files

**Comment by ScottHuangZL** [comment]
Hi @nadar ,  

How about your server host multiple web sites? Usually people just put them under folder c:\xampp\htdocs with different folders, and set root to htdocs. We set .htaccess in each folder to control the access right. We would like the different sites(may be use yii1.1 or yii2.0 in different folders) also can co-work together easily.

Or you plan setup multiple virtual host in conf/extra/httpd-vhosts.conf?


Thanks.

**Comment by nadar** [comment]
In general people do assign a vritual hosts a given domain, this is also what websites hosters does. Also with Yii 1/2 - https://github.com/yiisoft/yii2-app-basic - the directory is named `web` but its the same as we do only with a different name `public_html`. 

So i think its not a LUYA specific issue, its more an issue about how you configure your webserver.

**Comment by nadar** [comment]
btw. yes @ScottHuangZL the `httpd-vhosts.conf` would be the right place i assume.

**Pull request closed without merging**
